version: '3'

services:

  postgres:
    image: 'postgres:15'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 777
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql